<?php 
require('config/Config.php');
require('basedatos/Conection.php');
require('basedatos/ORMysql.php');
require('basedatos/ORMPostgres.php');
require('basedatos/ORM.php');
require('basedatos/Model.php');
require('route/Route.php');
require('view/View.php');
require('helpers/Helpers.php');
require('config/Session.php');
?>